Repository htm-community/htm.core, pull requests merged in 2018-11, with the labels that each got.

#61 Convert tests & examples to unit tests
  .travis.yml
  README.md
  appveyor.yml
  circle.yml
  src/CMakeLists.txt
  src/examples/Profiling.md
  src/test/unit/algorithms/ConnectionsPerformanceTest.cpp
  src/test/unit/algorithms/ConnectionsPerformanceTest.hpp
  src/test/unit/algorithms/HelloSPTPTest.cpp
  src/test/unit/algorithms/Serialization.cpp
  src/test/unit/engine/CppRegionTest.cpp
  src/test/unit/engine/Data.csv
  src/test/unit/engine/HelloRegionTest.cpp
  src/test/unit/engine/PyRegionTest.cpp
Labels: ready

#89 Test fix performance
  src/test/unit/algorithms/ConnectionsPerformanceTest.cpp
  src/test/unit/algorithms/ConnectionsPerformanceTest.hpp
  src/test/unit/algorithms/HelloSPTPTest.cpp
Labels: code, ready, tooling

#90 Ci travis: update Xenial & g++7
  .travis.yml
  circle.yml
Labels: build, ready

#107 no_APR_Step4
  src/nupic/engine/NuPIC.cpp
  src/nupic/math/GraphAlgorithms.hpp
  src/nupic/os/Directory.cpp
  src/nupic/os/Directory.hpp
  src/nupic/os/ImportFilesystem.hpp
  src/nupic/os/OS.cpp
  src/nupic/os/Path.cpp
  src/nupic/os/Path.hpp
  src/nupic/os/Timer.cpp
  src/nupic/os/Timer.hpp
  src/nupic/utils/StringUtils.cpp
  src/nupic/utils/StringUtils.hpp
  src/test/unit/os/DirectoryTest.cpp
  src/test/unit/os/PathTest.cpp
Labels: code, ready

#10 Add Sliding window
  src/CMakeLists.txt
  src/nupic/utils/MovingAverage.cpp
  src/nupic/utils/MovingAverage.hpp
  src/nupic/utils/SlidingWindow.hpp
  src/test/unit/utils/MovingAverageTest.cpp
  src/test/unit/utils/SlidingWindowTest.cpp
Labels: backport_upstream, code, enhancement, help wanted, ready

#116 PerformanceTests: reduce runtime for TP test
  src/test/unit/algorithms/ConnectionsPerformanceTest.cpp
Labels: optimization, ready

#113 SDR class
  src/CMakeLists.txt
  src/nupic/ntypes/Sdr.hpp
  src/nupic/types/Types.h
  src/test/unit/ntypes/SdrTest.cpp
Labels: ready

#83 Random std:: implementation
  DEPENDENCIES.md
  Dockerfile
  README.md
  bindings/py/tests/algorithms/cells4_test.py
  bindings/py/tests/nupic_random_test.py
  src/CMakeLists.txt
  src/nupic/algorithms/Cells4.cpp
  src/nupic/algorithms/Cells4.hpp
  src/nupic/algorithms/Segment.cpp
  src/nupic/algorithms/SegmentUpdate.hpp
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/engine/Network.cpp
  src/nupic/math/DenseMatrix.hpp
  src/nupic/utils/Random.cpp
  src/nupic/utils/Random.hpp
  src/nupic/utils/TRandom.cpp
  src/nupic/utils/TRandom.hpp
  src/test/unit/algorithms/ConnectionsPerformanceTest.cpp
  src/test/unit/algorithms/Serialization.cpp
  src/test/unit/utils/RandomPrivateOrig.c
  src/test/unit/utils/RandomTest.cpp
Labels: ready

#46 backtracking TM
  external/common/include/cycle_counter.hpp
  src/CMakeLists.txt
  src/nupic/algorithms/BacktrackingTMCpp.cpp
  src/nupic/algorithms/BacktrackingTMCpp.hpp
  src/nupic/algorithms/Cells4.cpp
  src/nupic/algorithms/Cells4.hpp
  src/nupic/algorithms/Segment.cpp
  src/nupic/algorithms/Segment.hpp
  src/nupic/algorithms/SegmentUpdate.cpp
  src/nupic/algorithms/SegmentUpdate.hpp
  src/nupic/utils/Random.cpp
  src/nupic/utils/Random.hpp
  src/test/unit/algorithms/BacktrackingTMCppTest.cpp
  src/test/unit/algorithms/Cells4Test.cpp
  src/test/unit/utils/RandomTest.cpp
Labels: TM, backport_upstream, code, community, enhancement, feature, ready

#11 Anomaly likelihood
  src/CMakeLists.txt
  src/nupic/algorithms/Anomaly.cpp
  src/nupic/algorithms/Anomaly.hpp
  src/nupic/algorithms/AnomalyLikelihood.cpp
  src/nupic/algorithms/AnomalyLikelihood.hpp
  src/test/unit/algorithms/AnomalyTest.cpp
Labels: anomaly, backport_upstream, community, enhancement, feature, help wanted, ready

#133 SP equals
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/algorithms/SpatialPooler.hpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
Labels: SP, code, enhancement, ready
