Repository htm-community/htm.core, pull requests merged in 2018-08, with the labels that each got.

#52 Adding smart pointers and new features to ArrayBase and friends.
  src/nupic/ntypes/Array.hpp
  src/nupic/ntypes/ArrayBase.cpp
  src/nupic/ntypes/ArrayBase.hpp
  src/nupic/ntypes/ArrayRef.hpp
  src/nupic/types/BasicType.cpp
  src/nupic/types/BasicType.hpp
  src/test/unit/ntypes/ArrayTest.cpp
  src/test/unit/types/BasicTypeTest.cpp
Labels: backport_upstream, code, community

#56 Master numenta update
  src/nupic/engine/Output.hpp
Labels: upstream

#71 Remove gabor & ImageSensor
  bindings/py/tests/algorithms/svm_test.py
  src/CMakeLists.txt
  src/nupic/algorithms/GaborNode.cpp
  src/nupic/algorithms/GaborNode.hpp
  src/nupic/algorithms/ImageSensorLite.cpp
  src/nupic/algorithms/ImageSensorLite.hpp
  src/nupic/algorithms/Svm.cpp
  src/nupic/algorithms/Svm.hpp
  src/nupic/algorithms/SvmT.hpp
  src/nupic/bindings/algorithms.i
  src/nupic/math/Convolution.hpp
  src/nupic/math/Erosion.hpp
  src/nupic/math/Rotation.hpp
  src/test/unit/algorithms/SvmTest.cpp
Labels: backport_upstream, code, ready
