Repository htm-community/htm.core, pull requests merged in 2018-12, with the labels that each got.

#132 Fix encoder outputtype to UInt, avoids conversions
  src/CMakeLists.txt
  src/nupic/encoders/ScalarEncoder.cpp
  src/nupic/encoders/ScalarEncoder.hpp
  src/nupic/engine/RegionImplFactory.cpp
  src/nupic/os/Timer.cpp
  src/nupic/os/Timer.hpp
  src/nupic/regions/ScalarSensor.cpp
  src/nupic/regions/ScalarSensor.hpp
  src/test/unit/algorithms/ConnectionsPerformanceTest.cpp
  src/test/unit/algorithms/HelloSPTPTest.cpp
  src/test/unit/encoders/ScalarEncoderTest.cpp
Labels: API_BREAKING_CHANGE, code, encoder, ready

#126 SDR_Proxy
  src/nupic/ntypes/Sdr.hpp
  src/test/unit/ntypes/SdrTest.cpp
Labels: enhancement, ready

#127 SP-SDR Integration
  bindings/py/src/bindings/algorithms/py_SpatialPooler.cpp
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/algorithms/SpatialPooler.hpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
Labels: SP, code, enhancement, optimization

#138 WIP Hotgym benchmark in C++ classes
  external/common/include/csv.h
  src/CMakeLists.txt
  src/examples/HelloSPTP.cpp
  src/examples/Hotgym.cpp
  src/nupic/algorithms/Anomaly.hpp
  src/nupic/algorithms/BacktrackingTMCpp.cpp
  src/test/unit/algorithms/HelloSPTPTest.cpp
Labels: in_progress, optimization, tests

#151 Remove SP.synPermTrim
  API_CHANGELOG.md
  bindings/py/src/bindings/algorithms/py_SpatialPooler.cpp
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/algorithms/SpatialPooler.hpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
Labels: API_BREAKING_CHANGE

#159 A minimal Boost build
  .travis.yml
  CMakeLists.txt
  CommonCompilerConfig.cmake
  circle.yml
  external/Boost.cmake
  external/CMakeLists.txt
  src/CombineUnixArchives.cmake
Labels: build, tooling

#153 SP-Connections Integration
  API_CHANGELOG.md
  bindings/py/src/bindings/algorithms/py_SpatialPooler.cpp
  src/examples/HelloSPTP.cpp
  src/nupic/algorithms/Connections.cpp
  src/nupic/algorithms/Connections.hpp
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/algorithms/SpatialPooler.hpp
  src/nupic/algorithms/TemporalMemory.cpp
  src/nupic/os/Timer.cpp
  src/nupic/os/Timer.hpp
  src/test/CMakeLists.txt
  src/test/unit/algorithms/ConnectionsTest.cpp
  src/test/unit/algorithms/Serialization.cpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
  src/test/unit/utils/RandomTest.cpp
Labels: SP, code, optimization

#168 README_updates
  .gitignore
  API_CHANGELOG.md
  README.md
Labels: documentation

#172 SDR fixes for Release mode compile.
  src/nupic/ntypes/Sdr.hpp
  src/test/CMakeLists.txt
Labels: code

#174 Faster debug tests
  src/examples/HelloSPTP.cpp
Labels: ready, tests

#176 OSX_build problem
  bindings/py/cpp_src/bindings/math/py_Random.cpp
  bindings/py/packaging/setup.py
  bindings/py/packaging/src/nupic/bindings/__init__.py
  bindings/py/tests/network_test.py
  circle.yml
Labels: fix, high, ready

#170 SDR Classifier without densematrix
  src/nupic/algorithms/SDRClassifier.cpp
  src/nupic/algorithms/SDRClassifier.hpp
  src/nupic/math/ArrayAlgo.hpp
  src/test/unit/algorithms/SDRClassifierTest.cpp
Labels: backport_upstream, bug, code, ready

#178 Fixed. TabError
  bindings/py/packaging/setup.py
Labels: code

#181 Fix markdown syntax
  API_CHANGELOG.md
Labels: documentation

#182 ConnectionsPerformanceTest: make trivially fast for Debug
  src/test/unit/algorithms/ConnectionsPerformanceTest.cpp
Labels: tests

#187 getSpec_bug
  bindings/py/cpp_src/bindings/engine/py_Engine.cpp
  bindings/py/cpp_src/plugin/RegisteredRegionImplPy.hpp
  bindings/py/tests/network_test.py
  src/nupic/engine/Network.cpp
  src/nupic/engine/Region.cpp
  src/nupic/engine/Region.hpp
  src/nupic/engine/RegionImplFactory.cpp
  src/nupic/engine/RegionImplFactory.hpp
  src/nupic/engine/RegisteredRegionImplCpp.hpp
  src/nupic/types/ptr_types.hpp
  src/test/unit/engine/LinkTest.cpp
Labels: NetworkAPI, fix, ready
