Repository htm-community/htm.core, pull requests merged in 2019-07, with the labels that each got.

#530 Use bytes on pickle SpatialPooler and TemporalMemory
  bindings/py/cpp_src/bindings/algorithms/py_SpatialPooler.cpp
  bindings/py/cpp_src/bindings/algorithms/py_TemporalMemory.cpp
  bindings/py/tests/algorithms/spatial_pooler_test.py
  bindings/py/tests/nupic_random_test.py
  bindings/py/tests/temporal_memory_test.py
Labels: Python Binding, SP, TM, fix, serializable

#540 SP remove unused calculateOverlapPct_()
  src/examples/hotgym/HelloSPTP.cpp
  src/htm/algorithms/SpatialPooler.cpp
  src/htm/algorithms/SpatialPooler.hpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
Labels: SP, code, ready

#534 Memory footprint
  src/examples/hotgym/HelloSPTP.cpp
  src/htm/algorithms/Connections.cpp
  src/htm/algorithms/Connections.hpp
  src/htm/algorithms/SpatialPooler.cpp
  src/htm/algorithms/SpatialPooler.hpp
  src/htm/algorithms/TemporalMemory.hpp
  src/htm/utils/VectorHelpers.hpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
  src/test/unit/engine/CppRegionTest.cpp
  src/test/unit/regions/TMRegionTest.cpp
Labels: code, ready

#533 MNIST params
  src/examples/mnist/MNIST_SP.cpp
  src/htm/algorithms/SpatialPooler.cpp
  src/htm/algorithms/SpatialPooler.hpp
  src/htm/algorithms/TemporalMemory.cpp
  src/htm/types/Sdr.cpp
  src/htm/utils/GroupBy.hpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
Labels: example, ready

#543 Connnections: use unordered_map for performance
  src/examples/hotgym/HelloSPTP.cpp
  src/htm/algorithms/Connections.hpp
  src/htm/algorithms/TemporalMemory.cpp
Labels: code, optimization, ready

#555 MNIST baseline model: no SP, directly raw images to classifier, 90.5%
  src/examples/mnist/MNIST_SP.cpp
  src/htm/algorithms/SpatialPooler.cpp
Labels: example, ready

#466 New method Connections::synapseCompetiton
  bindings/py/cpp_src/bindings/algorithms/py_Connections.cpp
  docs/synapse_competition.docx
  src/htm/algorithms/Connections.cpp
  src/htm/algorithms/Connections.hpp
  src/test/unit/algorithms/ConnectionsTest.cpp
Labels: feature, ready, research

#549 SP: remove numActiveColumnsPerInhArea
  API_CHANGELOG.md
  CommonCompilerConfig.cmake
  bindings/py/cpp_src/bindings/algorithms/py_SpatialPooler.cpp
  src/examples/hotgym/HelloSPTP.cpp
  src/examples/mnist/MNIST_SP.cpp
  src/htm/algorithms/SpatialPooler.cpp
  src/htm/algorithms/SpatialPooler.hpp
  src/htm/regions/SPRegion.cpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
  src/test/unit/engine/CppRegionTest.cpp
  src/test/unit/regions/SPRegionTest.cpp
  src/test/unit/regions/TMRegionTest.cpp
Labels: API_BREAKING_CHANGE, SP, code, ready

#564 Connections: microoptimizations
  src/examples/hotgym/HelloSPTP.cpp
  src/examples/mnist/MNIST_SP.cpp
  src/htm/algorithms/Connections.cpp
  src/htm/algorithms/Connections.hpp
  src/htm/algorithms/SpatialPooler.cpp
  src/htm/algorithms/SpatialPooler.hpp
Labels: optimization, ready

#567 Revert "SP measure time inh/overlaps/other in compute()"
  src/examples/hotgym/HelloSPTP.cpp
  src/examples/mnist/MNIST_SP.cpp
  src/htm/algorithms/SpatialPooler.cpp
  src/htm/algorithms/SpatialPooler.hpp
Labels: ready

#566 Fix Hot Gym Python Example
  py/htm/examples/hotgym.py
  py/htm/examples/mnist.py
Labels: example, python, ready

#571 Fixed particle swarming optimization
  py/htm/examples/mnist.py
  py/htm/optimization/swarming.py
Labels: code, fix, ready, tooling

#537 TM Connections integration
  bindings/py/cpp_src/bindings/algorithms/py_Connections.cpp
  src/examples/hotgym/HelloSPTP.cpp
  src/htm/algorithms/Connections.cpp
  src/htm/algorithms/Connections.hpp
  src/htm/algorithms/SpatialPooler.cpp
  src/htm/algorithms/SpatialPooler.hpp
  src/htm/algorithms/TemporalMemory.cpp
  src/htm/algorithms/TemporalMemory.hpp
  src/test/unit/algorithms/ConnectionsTest.cpp
  src/test/unit/algorithms/TemporalMemoryTest.cpp
Labels: TM, code, ready

#541 Anomaly likelihood
  py/htm/algorithms/anomaly_likelihood.py
  py/tests/algorithms/anomaly_likelihood_test.py
Labels: anomaly

#576 Connections:synapsesForPresynapticCell fix
  src/htm/algorithms/Connections.cpp
Labels: ready

#580 SDR concat fix const signature
  src/htm/types/Sdr.cpp
  src/htm/types/Sdr.hpp
  src/test/unit/types/SdrTest.cpp
Labels: ready, sdr

#583 Update dayOfWeek encoder
  py/tests/encoders/date_test.py
Labels: python, tests

#581 Force X64 build in setup.py for Windows
  bindings/py/packaging/setup.py
  src/htm/algorithms/TemporalMemory.cpp
Labels: build, platform

#589 Py hotgym cleanup
  py/htm/examples/hotgym.py
Labels: example, python, ready

#593 Do not require operator== for region implementation.
  src/htm/engine/RegionImpl.hpp
  src/test/unit/regions/SPRegionTest.cpp
Labels: NetworkAPI, python, ready
