Repository htm-community/htm.core, pull requests merged in 2019-10, with the labels that each got.

#694 Verify Wheel
  .github/workflows/htmcore.yml
  .gitignore
  bindings/py/README.md
  bindings/py/cpp_src/CMakeLists.txt
  bindings/py/packaging/setup.py
  bindings/py/tests/__init__.py
  bindings/py/tests/algorithms/temporal_memory_test.py
  bindings/py/tests/check_test.py
  bindings/py/tests/nupic_random_test.py
  bindings/py/tests/regions/network_test.py
  bindings/py/tests/regions/pyregion_test.py
  bindings/py/tests/sparse_link_test.py
  external/YamlCppLib.cmake
  setup.py
Labels: build, in_progress, python

#677 Pybind11 update to 2.4.2
  .github/workflows/htmcore.yml
  .gitignore
  external/pybind11.cmake
Labels: dependencies, ready

#705 PyPI release & Readme
  .github/workflows/arm64-build.yml
  .github/workflows/build.yml
  Dockerfile
  README.md
Labels: documentation, tooling

#711 Docker: try running make -j8
  Dockerfile
Labels: build, platform, tooling

#713 Python examples fixes
  VERSION
  bindings/py/tests/algorithms/sdr_classifier_test.py
  py/htm/examples/hotgym.py
  py/htm/examples/sp/sp_tutorial.py
  src/htm/algorithms/SDRClassifier.cpp
  src/htm/algorithms/SDRClassifier.hpp
Labels: ready

#715 New YAML parser interface
  .clang-format
  bindings/py/cpp_src/plugin/PyBindRegion.cpp
  bindings/py/cpp_src/plugin/RegisteredRegionImplPy.hpp
  bindings/py/packaging/src/htm/bindings/tools/serialization_test_py_region.py
  external/CMakeLists.txt
  external/YamlCppLib.cmake
  external/bootstrap.cmake
  external/libYaml.cmake
  py/htm/advanced/regions/GridCellLocationRegion.py
  src/CMakeLists.txt
  src/htm/algorithms/SDRClassifier.cpp
  src/htm/engine/RegionImpl.cpp
  src/htm/engine/RegionImpl.hpp
  src/htm/engine/RegionImplFactory.cpp
  src/htm/engine/RegionImplFactory.hpp
  src/htm/engine/RegisteredRegionImpl.hpp
  src/htm/engine/RegisteredRegionImplCpp.hpp
  src/htm/engine/YAMLUtils.cpp
  src/htm/engine/YAMLUtils.hpp
  src/htm/ntypes/Scalar.cpp
  src/htm/ntypes/Scalar.hpp
  src/htm/ntypes/Value.cpp
  src/htm/ntypes/Value.hpp
  src/htm/regions/SPRegion.cpp
  src/htm/regions/SPRegion.hpp
  src/htm/regions/ScalarSensor.cpp
  src/htm/regions/ScalarSensor.hpp
  src/htm/regions/TMRegion.cpp
  src/htm/regions/TestNode.cpp
  src/htm/regions/VectorFileEffector.cpp
  src/htm/regions/VectorFileEffector.hpp
  src/htm/regions/VectorFileSensor.cpp
  src/htm/regions/VectorFileSensor.hpp
  src/test/CMakeLists.txt
  src/test/unit/engine/CppRegionTest.cpp
  src/test/unit/engine/YAMLUtilsTest.cpp
  src/test/unit/ntypes/ScalarTest.cpp
  src/test/unit/ntypes/ValueTest.cpp
  src/test/unit/regions/RegionTestUtilities.cpp
  src/test/unit/regions/SPRegionTest.cpp
  src/test/unit/regions/TMRegionTest.cpp
  src/test/unit/regions/VectorFileTest.cpp
Labels: NetworkAPI, in_progress, low

#708 Readme: document cmake installation from pip
  README.md
Labels: dependencies, documentation, ready

#723 fix comparison on ARM
  Dockerfile
  src/htm/ntypes/Value.cpp
Labels: ready

#724 30% speedup of ColumnPooler
  py/htm/advanced/algorithms/column_pooler.py
  py/htm/advanced/algorithms/location_modules.py
Labels: optimization, python

#725 switch from building with distutils to setuptools in setup.py
  .github/workflows/build.yml
  requirements.txt
  setup.py
Labels: build, ready

#726 Using Create rather than Read Access in python regions
  bindings/py/cpp_src/CMakeLists.txt
  bindings/py/cpp_src/plugin/PyBindRegion.cpp
  external/pybind11.cmake
  py/htm/advanced/regions/ApicalTMPairRegion.py
  py/htm/advanced/regions/ApicalTMSequenceRegion.py
  py/htm/advanced/regions/ColumnPoolerRegion.py
  py/htm/advanced/regions/GridCellLocationRegion.py
  py/htm/advanced/regions/RawSensor.py
  py/htm/advanced/regions/RawValues.py
  src/htm/engine/Spec.cpp
  src/htm/ntypes/BasicType.cpp
Labels: NetworkAPI, Python Binding, ready

#728 Dependencies: update cereal to 1.3.0
  external/cereal.cmake
Labels: dependencies, ready

#727 all dependencies are tied to specific tag/commit version
  external/README.md
  external/libYaml.cmake
  external/mnist_data.cmake
Labels: ready

#733 Readme: add citation format for htm.core
  README.md
Labels: documentation, ready

#735 Docker arm tests
  .github/workflows/build.yml
  Dockerfile
  src/test/unit/algorithms/SpatialPoolerTest.cpp
Labels: platform, tests, tooling
