Repository htm-community/htm.core, pull requests merged in 2019-08, with the labels that each got.

#586 Force 64bit windows build
  bindings/py/packaging/setup.py
  external/CMakeLists.txt
  external/bootstrap.cmake
  startupMSVC.bat
Labels: bug, build, platform

#552 Connections::computeActivity returns overlap
  API_CHANGELOG.md
  bindings/py/cpp_src/bindings/algorithms/py_Connections.cpp
  bindings/py/cpp_src/bindings/algorithms/py_SpatialPooler.cpp
  src/htm/algorithms/Connections.cpp
  src/htm/algorithms/Connections.hpp
  src/htm/algorithms/SpatialPooler.cpp
  src/htm/algorithms/SpatialPooler.hpp
  src/htm/algorithms/TemporalMemory.cpp
  src/test/unit/algorithms/ConnectionsTest.cpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
Labels: code, ready

#597 Speed up Docker builds (no more NumPy source build)
  .circleci/config.yml
  Dockerfile
  README.md
  src/examples/hotgym/HelloSPTP.cpp
Labels: build, platform, tooling

#611 Avoid -Wimplicit-fallthrough in GCC6
  src/htm/types/Serializable.hpp
Labels: build, platform

#582 Datetime enc fix dayOfWeek crash with Monday 00:00
  bindings/py/tests/encoders/scalar_encoder_test.py
  py/htm/encoders/date.py
  py/htm/encoders/scalar_encoder.py
  py/htm/examples/__init__.py
  py/htm/examples/scalar_encoder.py
  py/tests/encoders/date_test.py
  src/htm/encoders/ScalarEncoder.cpp
Labels: encoder, python, ready

#604 TM static methods made private
  src/htm/algorithms/Connections.cpp
  src/htm/algorithms/SpatialPooler.hpp
  src/htm/algorithms/TemporalMemory.cpp
  src/htm/algorithms/TemporalMemory.hpp
Labels: code, ready

#613 implemented bindings on getParameterArray and setParameterArray
  bindings/py/cpp_src/bindings/engine/py_Engine.cpp
  bindings/py/tests/network_test.py
  src/htm/engine/Region.cpp
  src/htm/engine/Region.hpp
  src/htm/engine/RegionImpl.cpp
  src/htm/ntypes/BasicType.cpp
  src/htm/regions/TestNode.cpp
  startupMSVC.bat
Labels: NetworkAPI, ready

#614 Travis bionic
  .travis.yml
  bindings/py/packaging/requirements.txt
  bindings/py/tests/algorithms/temporal_memory_test.py
Labels: Python Binding, ready, tooling

#588 TM anomaly: new modes: likelihood,...
  bindings/py/cpp_src/bindings/algorithms/py_TemporalMemory.cpp
  src/htm/algorithms/AnomalyLikelihood.cpp
  src/htm/algorithms/TemporalMemory.cpp
  src/htm/algorithms/TemporalMemory.hpp
  src/test/unit/algorithms/ConnectionsPerformanceTest.cpp
Labels: TM, anomaly, ready

#573 Binary deployment package creation
  .circleci/config.yml
  .travis.yml
  CMakeLists.txt
  README.md
  appveyor.yml
  bindings/py/cpp_src/CMakeLists.txt
  bindings/py/packaging/setup.py
  setup.cfg
  src/CMakeLists.txt
Labels: ready, tooling

#615 OSX CI: bump to XCode 11
  .circleci/config.yml
  CommonCompilerConfig.cmake
  bindings/py/packaging/setup.py
Labels: platform, ready, tooling

#631 Ci artefacts
  .circleci/config.yml
  .travis.yml
  appveyor.yml
  ci/fetch-artifacts.sh
Labels: in_progress, tooling

#632 added versioning from git tags
  CMakeLists.txt
  VERSION
  appveyor.yml
  src/CMakeLists.txt
  versioning.cmake
Labels: ready, tooling

#636 Pypi deploy
  .travis.yml
  ci/fetch-artifacts.sh
Labels: ready, tooling

#638 Python2 should still be supported
  bindings/py/packaging/setup.py
Labels: Python Binding, ready

#644 Fixed pickling on SP
  bindings/py/cpp_src/bindings/algorithms/py_SpatialPooler.cpp
  bindings/py/cpp_src/bindings/algorithms/py_TemporalMemory.cpp
  bindings/py/tests/algorithms/spatial_pooler_test.py
  bindings/py/tests/algorithms/temporal_memory_test.py
Labels: Python Binding, fix, ready, serializable

#603 SimHash Document Encoder in C++ with Python bindings
  README.md
  bindings/py/cpp_src/CMakeLists.txt
  bindings/py/cpp_src/bindings/encoders/encoders_module.cpp
  bindings/py/cpp_src/bindings/encoders/py_RDSE.cpp
  bindings/py/cpp_src/bindings/encoders/py_ScalarEncoder.cpp
  bindings/py/cpp_src/bindings/encoders/py_SimHashDocumentEncoder.cpp
  bindings/py/tests/encoders/simhash_document_encoder_test.py
  external/CMakeLists.txt
  external/README.md
  external/bootstrap.cmake
  external/digestpp.cmake
  py/htm/encoders/rdse.py
  py/htm/encoders/simhash_document_encoder.py
  py/htm/examples/encoders/__init__.py
  py/htm/examples/encoders/rdse.py
  py/htm/examples/encoders/scalar_encoder.py
  py/htm/examples/encoders/simhash_document_encoder.py
  src/CMakeLists.txt
  src/htm/encoders/RandomDistributedScalarEncoder.hpp
  src/htm/encoders/ScalarEncoder.hpp
  src/htm/encoders/SimHashDocumentEncoder.README.md
  src/htm/encoders/SimHashDocumentEncoder.cpp
  src/htm/encoders/SimHashDocumentEncoder.hpp
  src/test/CMakeLists.txt
  src/test/unit/encoders/SimHashDocumentEncoderTest.cpp
Labels: encoder, enhancement, ready

#647 Deployment where each CI uploads its own artifacts
  .circleci/config.yml
  .travis.yml
  appveyor.yml
Labels: build, ready

#648 Trying to deploy only on tagged builds
  .circleci/config.yml
  appveyor.yml
Labels: build, ready

#649 Testing deployment. Part5.
  .circleci/config.yml
  .travis.yml
  appveyor.yml
Labels: ready

#650 Trying to get a tagged master build for deployment, Try 6
  .circleci/config.yml
  .travis.yml
  appveyor.yml
Labels: ready
