Repository htm-community/htm.core, pull requests merged in 2019-09, with the labels that each got.

#608 RDSE: serialization for py bindings
  bindings/py/cpp_src/bindings/encoders/py_RDSE.cpp
  bindings/py/tests/encoders/rdse_test.py
Labels: Python Binding, encoder, ready, serializable

#655 Added getOutputArray(), getInputArray(), and setInputArray()
  bindings/py/cpp_src/bindings/engine/py_Engine.cpp
  bindings/py/cpp_src/plugin/PyBindRegion.cpp
  bindings/py/packaging/src/htm/bindings/regions/PyRegion.py
  bindings/py/tests/network_test.py
  src/htm/engine/Network.hpp
  src/htm/engine/Region.cpp
  src/htm/engine/Region.hpp
  src/htm/regions/TMRegion.cpp
Labels: NetworkAPI, Python Binding, ready

#660 OS.hpp removed as unused
  bindings/py/cpp_src/CMakeLists.txt
  bindings/py/cpp_src/bindings/engine/engine_module.cpp
  bindings/py/cpp_src/bindings/engine/py_Engine.cpp
  bindings/py/cpp_src/bindings/engine/py_OS.cpp
  src/CMakeLists.txt
  src/htm/engine/RegionImplFactory.cpp
  src/htm/os/Directory.cpp
  src/htm/os/OS.cpp
  src/htm/os/OS.hpp
  src/htm/os/OSUnix.cpp
  src/htm/os/OSWin.cpp
  src/htm/os/Path.cpp
  src/test/CMakeLists.txt
  src/test/unit/ntypes/ArrayTest.cpp
  src/test/unit/os/DirectoryTest.cpp
  src/test/unit/os/OSTest.cpp
  src/test/unit/os/PathTest.cpp
Labels: ready

#661 Created first python temporal memory test
  bindings/py/tests/algorithms/temporal_memory_test.py
Labels: Python Binding, tests

#670 Enhancement of bindings for executeCommand()
  bindings/py/cpp_src/bindings/engine/py_Engine.cpp
  bindings/py/tests/network_test.py
  src/htm/regions/TestNode.cpp
Labels: NetworkAPI, Python Binding, ready

#572 Optimization example + doc
  .gitignore
  py/htm/examples/mnist.py
  py/htm/optimization/README.md
  py/htm/optimization/swarming.py
Labels: documentation, example, ready

#594 Clang-9 compatible with our codebase
  CommonCompilerConfig.cmake
Labels: build, ready

#672 Htmresearch port cleanup
  bindings/py/tests/regions/network_test.py
  bindings/py/tests/regions/pyregion_test.py
  bindings/py/tests/regions/sp_region_test.py
  py/tests/advanced/regions/region_init_test.py
Labels: ready

#673 Changed SPRegion "synPermConnected" parameter access from ReadOnly to
  bindings/py/tests/regions/sp_region_test.py
  src/htm/regions/SPRegion.cpp
Labels: NetworkAPI

#674 Port of nupic CoordinateEncoder to htm.core and Python3
  py/htm/encoders/coordinate.py
  py/tests/encoders/coordinate_test.py
Labels: community, encoder, python

#676 Port of thalamus code from htmresearch
  bindings/py/packaging/requirements.txt
  py/htm/advanced/algorithms/connections.py
  py/htm/advanced/algorithms/thalamus.py
  py/htm/advanced/examples/thalamus/README.md
  py/htm/advanced/examples/thalamus/__init__.py
  py/htm/advanced/examples/thalamus/cajal.jpg
  py/htm/advanced/examples/thalamus/run_thalamus_experiment.py
  py/htm/advanced/examples/thalamus/thalamus_utils.py
  py/tests/advanced/algorithms/thalamus_test.py
Labels: python, research

#678 Py datasets downloaded from openML
  bindings/py/packaging/requirements.txt
  py/htm/examples/mnist.py
Labels: example, python, ready

#667 SDRClassifier: fix precision by using Real64 for PDF
  bindings/py/cpp_src/bindings/algorithms/py_SDRClassifier.cpp
  bindings/py/tests/algorithms/sdr_classifier_test.py
  src/htm/algorithms/SDRClassifier.cpp
  src/htm/algorithms/SDRClassifier.hpp
  src/test/unit/algorithms/SDRClassifierTest.cpp
Labels: ready

#687 Allow compilation on gcc 9
  CommonCompilerConfig.cmake
  src/CMakeLists.txt
Labels: platform, ready

#686 Added format enums for Serialization to the Network bindings.
  bindings/py/cpp_src/bindings/engine/py_Engine.cpp
Labels: NetworkAPI, Python Binding, ready

#688 CI: try Github Actions as CI provider
  .circleci/config.yml
  .github/workflows/arm64-build.yml
  .github/workflows/htmcore.yml
  .travis.yml
  Dockerfile
  README.md
  appveyor.yml
  bindings/py/packaging/setup.py
  external/bootstrap.cmake
  requirements.txt
  src/CMakeLists.txt
  src/examples/hotgym/HelloSPTP.cpp
  src/test/unit/engine/CppRegionTest.cpp
Labels: build, platform, ready, tooling

#689 GH Actions: run on tag v* pushes
  .github/workflows/htmcore.yml
Labels: tooling

#690 PYPI works now only on Linux
  .github/workflows/htmcore.yml
  README.md
Labels: tooling

#692 removed unused StlIo.hpp
  VERSION
  src/CMakeLists.txt
  src/htm/utils/StlIo.cpp
  src/htm/utils/StlIo.hpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
  src/test/unit/algorithms/TemporalMemoryTest.cpp
Labels: ready

#693 PYPI: publish build artifacts
  .github/workflows/htmcore.yml
Labels: tooling

#697 set yaml-cpp to download version 0.6.3
  VERSION
  external/YamlCppLib.cmake
Labels: build, dependencies, ready
