Repository htm-community/htm.core, pull requests merged in 2019-02, with the labels that each got.

#225 SDR-Python bindings - WIP
  README.md
  bindings/py/cpp_src/CMakeLists.txt
  bindings/py/cpp_src/bindings/algorithms/algorithm_module.cpp
  bindings/py/cpp_src/bindings/algorithms/py_SDR.cpp
  bindings/py/cpp_src/bindings/algorithms/py_SDR_Metrics.cpp
  bindings/py/tests/SDR_Metrics_test.py
  bindings/py/tests/SDR_test.py
  src/nupic/ntypes/Sdr.hpp
  src/nupic/ntypes/SdrMetrics.hpp
  src/nupic/regions/VectorFileSensor.cpp
  src/nupic/utils/StringUtils.cpp
  src/test/unit/ntypes/SdrTest.cpp
Labels: Python Binding, enhancement, ready

#248 SDR Moved from ntypes/ to types/
  bindings/py/cpp_src/bindings/algorithms/py_SDR.cpp
  bindings/py/cpp_src/bindings/algorithms/py_SDR_Metrics.cpp
  src/CMakeLists.txt
  src/nupic/algorithms/Connections.hpp
  src/nupic/algorithms/SpatialPooler.hpp
  src/nupic/types/Sdr.hpp
  src/nupic/types/SdrProxy.hpp
  src/nupic/utils/SdrMetrics.hpp
  src/test/unit/algorithms/TemporalMemoryTest.cpp
  src/test/unit/ntypes/SdrMetricsTest.cpp
  src/test/unit/ntypes/SdrProxyTest.cpp
  src/test/unit/ntypes/SdrTest.cpp
Labels: code

#234 Adding SDR to NetworkAPI
  appveyor.yml
  bindings/py/cpp_src/bindings/engine/py_Engine.cpp
  bindings/py/cpp_src/bindings/math/py_SparseBinaryMatrix.cpp
  bindings/py/cpp_src/bindings/math/py_SparseMatrix.cpp
  bindings/py/cpp_src/bindings/math/py_SparseTensor.cpp
  bindings/py/cpp_src/plugin/PyBindRegion.cpp
  bindings/py/cpp_src/plugin/unittest/PyRegionTest.cpp
  bindings/py/tests/network_test.py
  src/CMakeLists.txt
  src/NupicLibraryUtils.cmake
  src/nupic/engine/Input.cpp
  src/nupic/engine/Input.hpp
  src/nupic/engine/Link.cpp
  src/nupic/engine/Link.hpp
  src/nupic/engine/Network.cpp
  src/nupic/engine/Output.cpp
  src/nupic/engine/Output.hpp
  src/nupic/engine/Region.cpp
  src/nupic/engine/Region.hpp
  src/nupic/engine/RegionImpl.hpp
  src/nupic/engine/Spec.cpp
  src/nupic/engine/Spec.hpp
  src/nupic/engine/TestFanIn2LinkPolicy.cpp
  src/nupic/math/Math.hpp
  src/nupic/math/SparseBinaryMatrix.hpp
  src/nupic/ntypes/Array.hpp
  src/nupic/ntypes/ArrayBase.cpp
  src/nupic/ntypes/ArrayBase.hpp
  src/nupic/ntypes/ArrayRef.hpp
  src/nupic/ntypes/Dimensions.cpp
  src/nupic/ntypes/Dimensions.hpp
  src/nupic/regions/TestNode.cpp
  src/nupic/regions/TestNode.hpp
  src/nupic/regions/VectorFileEffector.cpp
  src/nupic/regions/VectorFileEffector.hpp
  src/nupic/regions/VectorFileSensor.hpp
  src/nupic/types/BasicType.cpp
  src/nupic/types/Types.hpp
  src/test/unit/engine/CppRegionTest.cpp
  src/test/unit/engine/HelloRegionTest.cpp
  src/test/unit/engine/InputTest.cpp
  src/test/unit/engine/LinkTest.cpp
  src/test/unit/engine/UniformLinkPolicyTest.cpp
  src/test/unit/ntypes/ArrayTest.cpp
  src/test/unit/ntypes/DimensionsTest.cpp
  startupMSVC.bat
Labels: NetworkAPI, ready

#252 Connections raise permanence err
  src/nupic/algorithms/Connections.cpp
  src/test/unit/algorithms/ConnectionsTest.cpp
Labels: TM, code, ready

#251 Sdr split to hpp/cpp
  src/CMakeLists.txt
  src/nupic/types/Sdr.cpp
  src/nupic/types/Sdr.hpp
  src/test/unit/types/SdrTest.cpp
Labels: ready

#256 Hotgym 4
  bindings/py/cpp_src/bindings/algorithms/py_HTM.cpp
  src/examples/HelloSPTP.cpp
  src/nupic/algorithms/BacktrackingTMCpp.cpp
  src/nupic/algorithms/BacktrackingTMCpp.hpp
  src/nupic/algorithms/Connections.hpp
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/algorithms/SpatialPooler.hpp
  src/nupic/algorithms/TemporalMemory.cpp
  src/nupic/algorithms/TemporalMemory.hpp
  src/test/unit/algorithms/ConnectionsPerformanceTest.cpp
  src/test/unit/algorithms/HelloSPTPTest.cpp
  src/test/unit/algorithms/TemporalMemoryTest.cpp
Labels: bug, example, ready

#221 Removed Method Connections::setConnectedThreshold
  API_CHANGELOG.md
  bindings/py/cpp_src/bindings/algorithms/py_SpatialPooler.cpp
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/algorithms/SpatialPooler.hpp
  src/nupic/algorithms/TemporalMemory.cpp
  src/nupic/algorithms/TemporalMemory.hpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
Labels: API_BREAKING_CHANGE, SP, TM, ready

#261 Adds shared lib for Linux and OSx
  .travis.yml
  CMakeLists.txt
  CommonCompilerConfig.cmake
  README.md
  src/CMakeLists.txt
  src/ExpandStaticLib.cmake
  src/nupic/algorithms/InSynapse.hpp
  src/nupic/algorithms/SegmentUpdate.hpp
  src/nupic/engine/Region.hpp
  src/nupic/engine/RegionImpl.hpp
  src/nupic/os/Directory.cpp
  src/nupic/os/Directory.hpp
  src/nupic/os/Path.cpp
  src/nupic/os/Path.hpp
  src/nupic/regions/ScalarSensor.hpp
  src/nupic/types/Serializable.hpp
  src/test/CMakeLists.txt
  src/test/unit/os/DirectoryTest.cpp
Labels: ready

#269 Fix unit tests which randomly failed.
  bindings/py/tests/SDR_test.py
  src/test/unit/algorithms/TemporalMemoryTest.cpp
Labels: bug, fix, ready, tests

#244 Adding SPRegion region class
  src/CMakeLists.txt
  src/nupic/engine/Input.hpp
  src/nupic/engine/Link.cpp
  src/nupic/engine/Output.cpp
  src/nupic/engine/Region.cpp
  src/nupic/engine/Region.hpp
  src/nupic/engine/RegionImplFactory.cpp
  src/nupic/ntypes/Array.hpp
  src/nupic/ntypes/ArrayBase.cpp
  src/nupic/ntypes/ArrayBase.hpp
  src/nupic/regions/SPRegion.cpp
  src/nupic/regions/SPRegion.hpp
  src/nupic/regions/ScalarSensor.cpp
  src/nupic/regions/ScalarSensor.hpp
  src/nupic/regions/VectorFileEffector.cpp
  src/nupic/types/Sdr.cpp
  src/test/CMakeLists.txt
  src/test/unit/engine/InputTest.cpp
  src/test/unit/regions/RegionTestUtilities.cpp
  src/test/unit/regions/RegionTestUtilities.hpp
  src/test/unit/regions/SPRegionTest.cpp
Labels: NetworkAPI, SP, enhancement, ready

#268 Tp execution input size
  src/CMakeLists.txt
  src/examples/Hotgym.cpp
  src/examples/hotgym/HelloSPTP.cpp
  src/examples/hotgym/HelloSPTP.hpp
  src/examples/hotgym/Hotgym.cpp
  src/test/unit/algorithms/Cells4Test.cpp
  src/test/unit/algorithms/HelloSPTPTest.cpp
Labels: ready

#277 Remove MemParser & MemStream classes
  src/CMakeLists.txt
  src/nupic/engine/YAMLUtils.cpp
  src/nupic/ntypes/MemParser.cpp
  src/nupic/ntypes/MemParser.hpp
  src/nupic/ntypes/MemStream.hpp
  src/test/CMakeLists.txt
  src/test/unit/ntypes/MemParserTest.cpp
  src/test/unit/ntypes/MemStreamTest.cpp
  src/test/unit/utils/RandomTest.cpp
Labels: code, ready

#220 OSX XCode 10.1 bump
  CMakeLists.txt
  CommonCompilerConfig.cmake
  bindings/py/cpp_src/CMakeLists.txt
  circle.yml
Labels: build, platform, ready

#270 Sdr Tools
  bindings/py/cpp_src/bindings/algorithms/py_SDR.cpp
  bindings/py/tests/SDR_test.py
  src/nupic/types/Sdr.cpp
  src/nupic/types/Sdr.hpp
  src/nupic/types/SdrProxy.hpp
  src/test/unit/types/SdrProxyTest.cpp
  src/test/unit/types/SdrTest.cpp
Labels: encoder, feature, ready

#271 remove LinkPolicy
  API_CHANGELOG.md
  CommonCompilerConfig.cmake
  bindings/py/cpp_src/bindings/algorithms/py_SDR.cpp
  bindings/py/cpp_src/plugin/PyBindRegion.cpp
  bindings/py/cpp_src/plugin/PyBindRegion.hpp
  circle.yml
  src/CMakeLists.txt
  src/nupic/engine/Input.cpp
  src/nupic/engine/Input.hpp
  src/nupic/engine/Link.cpp
  src/nupic/engine/Link.hpp
  src/nupic/engine/LinkPolicy.hpp
  src/nupic/engine/LinkPolicyFactory.cpp
  src/nupic/engine/LinkPolicyFactory.hpp
  src/nupic/engine/Network.cpp
  src/nupic/engine/Output.cpp
  src/nupic/engine/Output.hpp
  src/nupic/engine/Region.cpp
  src/nupic/engine/Region.hpp
  src/nupic/engine/RegionImpl.cpp
  src/nupic/engine/RegionImpl.hpp
  src/nupic/engine/RegionImplFactory.cpp
  src/nupic/engine/RegisteredRegionImpl.hpp
  src/nupic/engine/Spec.cpp
  src/nupic/engine/Spec.hpp
  src/nupic/engine/TestFanIn2LinkPolicy.cpp
  src/nupic/engine/TestFanIn2LinkPolicy.hpp
  src/nupic/engine/UniformLinkPolicy.cpp
  src/nupic/engine/UniformLinkPolicy.hpp
  src/nupic/engine/Watcher.cpp
  src/nupic/engine/Watcher.hpp
  src/nupic/engine/YAMLUtils.cpp
  src/nupic/ntypes/Array.hpp
  src/nupic/ntypes/ArrayBase.cpp
  src/nupic/ntypes/ArrayBase.hpp
  src/nupic/ntypes/Dimensions.cpp
  src/nupic/ntypes/Dimensions.hpp
  src/nupic/regions/SPRegion.cpp
  src/nupic/regions/SPRegion.hpp
  src/nupic/regions/ScalarSensor.cpp
  src/nupic/regions/ScalarSensor.hpp
  src/nupic/regions/TestNode.cpp
  src/nupic/regions/TestNode.hpp
  src/nupic/regions/VectorFileEffector.cpp
  src/nupic/regions/VectorFileEffector.hpp
  src/nupic/regions/VectorFileSensor.cpp
  src/nupic/regions/VectorFileSensor.hpp
  src/nupic/types/Fraction.cpp
  src/nupic/types/Fraction.hpp
  src/nupic/types/Sdr.hpp
  src/nupic/types/SdrProxy.hpp
  src/test/CMakeLists.txt
  src/test/unit/engine/CppRegionTest.cpp
  src/test/unit/engine/HelloRegionTest.cpp
  src/test/unit/engine/InputTest.cpp
  src/test/unit/engine/LinkTest.cpp
  src/test/unit/engine/NetworkTest.cpp
  src/test/unit/engine/UniformLinkPolicyTest.cpp
  src/test/unit/engine/WatcherTest.cpp
  src/test/unit/types/FractionTest.cpp
Labels: API_BREAKING_CHANGE, NetworkAPI, ready

#242 MNIST example
  external/CMakeLists.txt
  external/bootstrap.cmake
  external/mnist_data.cmake
  src/CMakeLists.txt
  src/examples/hotgym/HelloSPTP.cpp
  src/examples/mnist/MNIST_SP.cpp
  src/nupic/algorithms/Connections.cpp
  src/nupic/algorithms/SDRClassifier.cpp
  src/nupic/algorithms/SDRClassifier.hpp
  src/nupic/algorithms/SpatialPooler.hpp
  src/nupic/types/Serializable.hpp
  src/test/CMakeLists.txt
  src/test/unit/algorithms/ConnectionsPerformanceTest.cpp
Labels: enhancement, example, help wanted, ready

#283 Temporal Memory - SDR integration - WIP
  src/nupic/algorithms/TemporalMemory.cpp
  src/nupic/algorithms/TemporalMemory.hpp
  src/test/unit/algorithms/TemporalMemoryTest.cpp
Labels: TM, enhancement
