Repository htm-community/htm.core, pull requests merged in 2019-03, with the labels that each got.

#290 Release Goals
  README.md
  RELEASE_V1_GOALS.md
Labels: community, documentation, ready

#292 Connections: adaptSegment make const input,
  src/nupic/algorithms/Connections.cpp
  src/nupic/algorithms/Connections.hpp
Labels: code, ready

#286 SP: strip unlearned columns: removed
  API_CHANGELOG.md
  bindings/py/cpp_src/bindings/algorithms/py_SpatialPooler.cpp
  src/examples/hotgym/HelloSPTP.cpp
  src/examples/mnist/MNIST_SP.cpp
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/algorithms/SpatialPooler.hpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
Labels: API_BREAKING_CHANGE, SP, low, question, ready

#296 SDR renamed data formats
  bindings/py/cpp_src/bindings/algorithms/py_SDR.cpp
  bindings/py/tests/SDR_test.py
  src/examples/mnist/MNIST_SP.cpp
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/algorithms/TemporalMemory.cpp
  src/nupic/regions/SPRegion.cpp
  src/nupic/types/Sdr.cpp
  src/nupic/types/Sdr.hpp
  src/nupic/types/SdrProxy.hpp
  src/nupic/utils/SdrMetrics.hpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
  src/test/unit/algorithms/TemporalMemoryTest.cpp
  src/test/unit/ntypes/ArrayTest.cpp
  src/test/unit/types/SdrProxyTest.cpp
  src/test/unit/types/SdrTest.cpp
Labels: code

#298 Rename SDR Proxy to Reshape
  bindings/py/cpp_src/bindings/algorithms/py_SDR.cpp
  bindings/py/tests/SDR_Metrics_test.py
  bindings/py/tests/SDR_test.py
  src/nupic/types/Sdr.hpp
  src/nupic/types/SdrProxy.hpp
  src/test/unit/types/SdrProxyTest.cpp
  src/test/unit/types/SdrTest.cpp
  src/test/unit/utils/SdrMetricsTest.cpp
Labels: code, ready

#301 ClassifierResult: add convenience getClass returning most probable label/classification
  API_CHANGELOG.md
  bindings/py/cpp_src/bindings/algorithms/py_SDRClassifier.cpp
  src/CMakeLists.txt
  src/examples/mnist/MNIST_SP.cpp
  src/nupic/algorithms/SDRClassifier.cpp
  src/nupic/algorithms/SDRClassifier.hpp
  src/nupic/types/ClassifierResult.cpp
  src/nupic/types/ClassifierResult.hpp
  src/test/unit/algorithms/SDRClassifierTest.cpp
Labels: API_BREAKING_CHANGE, ready

#303 Remove math/Types, StlIo cleanup
  src/CMakeLists.txt
  src/nupic/math/StlIo.hpp
  src/nupic/math/Types.hpp
Labels: code, ready

#305 TemporalMemory: fix handling of extra inputs & connectedPermanence
  src/nupic/algorithms/TemporalMemory.cpp
Labels: TM, bug, low, ready

#307 math/Utils: removed, removes support for I/O BigEndian files
  src/CMakeLists.txt
  src/nupic/math/Utils.hpp
  src/nupic/regions/VectorFile.cpp
  src/nupic/regions/VectorFile.hpp
Labels: NetworkAPI, code, ready

#315 Region Link changes, part 1 of PR #247
  bindings/py/cpp_src/plugin/PyBindRegion.cpp
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/engine/Input.cpp
  src/nupic/engine/Input.hpp
  src/nupic/engine/Link.cpp
  src/nupic/engine/Output.cpp
  src/nupic/engine/Output.hpp
  src/nupic/engine/Region.cpp
  src/nupic/engine/Region.hpp
  src/nupic/engine/RegionImpl.cpp
  src/nupic/engine/RegionImpl.hpp
  src/nupic/engine/RegionImplFactory.cpp
  src/nupic/engine/YAMLUtils.cpp
  src/nupic/ntypes/Array.hpp
  src/nupic/ntypes/ArrayBase.cpp
  src/nupic/ntypes/Dimensions.cpp
  src/nupic/ntypes/Value.cpp
  src/nupic/regions/SPRegion.cpp
  src/nupic/regions/SPRegion.hpp
  src/nupic/regions/TestNode.cpp
  src/nupic/regions/TestNode.hpp
  src/nupic/regions/VectorFileEffector.cpp
  src/nupic/regions/VectorFileSensor.cpp
  src/nupic/types/ClassifierResult.cpp
  src/nupic/types/Types.hpp
  src/nupic/utils/Log.hpp
  src/nupic/utils/LogItem.cpp
  src/nupic/utils/LogItem.hpp
  src/nupic/utils/LoggingException.cpp
  src/nupic/utils/VectorHelpers.hpp
  src/test/CMakeLists.txt
  src/test/unit/engine/CppRegionTest.cpp
  src/test/unit/engine/InputTest.cpp
  src/test/unit/regions/RegionTestUtilities.cpp
Labels: NetworkAPI, ready

#321 make mnist test Score: 88.91%
  src/examples/mnist/MNIST_SP.cpp
Labels: bug, example

#319 Changes requested on review of PR TMRegion
  DEVELOPER_NOTES.md
  bindings/py/cpp_src/bindings/engine/py_Engine.cpp
  src/nupic/engine/Input.hpp
  src/nupic/engine/Link.cpp
  src/nupic/ntypes/Array.hpp
  src/nupic/ntypes/ArrayBase.cpp
  src/nupic/ntypes/ArrayBase.hpp
  src/nupic/ntypes/Dimensions.cpp
  src/nupic/ntypes/Dimensions.hpp
  src/nupic/regions/SPRegion.cpp
  src/nupic/types/Serializable.hpp
  src/nupic/utils/Log.hpp
  src/nupic/utils/LogItem.hpp
  src/nupic/utils/VectorHelpers.hpp
  src/test/unit/engine/CppRegionTest.cpp
  src/test/unit/ntypes/ArrayTest.cpp
  src/test/unit/utils/VectorHelpersTest.cpp
Labels: NetworkAPI, code, ready

#317 Implement TMRegion
  src/CMakeLists.txt
  src/nupic/engine/RegionImplFactory.cpp
  src/nupic/regions/TMRegion.cpp
  src/nupic/regions/TMRegion.hpp
  src/test/CMakeLists.txt
  src/test/unit/regions/TMRegionTest.cpp
  startupMSVC.bat
Labels: NetworkAPI, ready

#322 TemporalMemory: Add python bindings for external inputs.
  bindings/py/cpp_src/bindings/algorithms/py_HTM.cpp
Labels: Python Binding, TM, fix, ready

#324 Compiler optimizations2
  CommonCompilerConfig.cmake
  src/nupic/algorithms/Connections.cpp
  src/nupic/algorithms/Connections.hpp
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/algorithms/SpatialPooler.hpp
  src/nupic/regions/TestNode.cpp
  src/nupic/types/Types.hpp
Labels: build, optimization, ready

#318 Add BacktrackingTMRegion
  src/CMakeLists.txt
  src/examples/hotgym/HelloSPTP.cpp
  src/nupic/algorithms/BacktrackingTM.cpp
  src/nupic/algorithms/BacktrackingTM.hpp
  src/nupic/engine/RegionImplFactory.cpp
  src/nupic/regions/BacktrackingTMRegion.cpp
  src/nupic/regions/BacktrackingTMRegion.hpp
  src/test/CMakeLists.txt
  src/test/unit/algorithms/BacktrackingTMTest.cpp
  src/test/unit/regions/BacktrackingTMRegionTest.cpp
Labels: NetworkAPI, ready

#326 SDR: implement assignment operator overload.
  src/nupic/types/Sdr.hpp
  src/test/unit/types/SdrTest.cpp
Labels: code, fix, sdr

#314 New class BaseEncoder
  API_CHANGELOG.md
  bindings/py/cpp_src/CMakeLists.txt
  bindings/py/cpp_src/bindings/encoders/encoders_module.cpp
  bindings/py/cpp_src/bindings/encoders/py_ScalarEncoder.cpp
  bindings/py/packaging/setup.py
  bindings/py/packaging/src/nupic/bindings/__init__.py
  bindings/py/tests/encoders/scalar_encoder_test.py
  src/CMakeLists.txt
  src/examples/hotgym/HelloSPTP.cpp
  src/nupic/encoders/BaseEncoder.hpp
  src/nupic/encoders/ScalarEncoder.cpp
  src/nupic/encoders/ScalarEncoder.hpp
  src/nupic/regions/ScalarSensor.cpp
  src/nupic/regions/ScalarSensor.hpp
  src/test/unit/encoders/ScalarEncoderTest.cpp
  src/test/unit/regions/SPRegionTest.cpp
  src/test/unit/regions/TMRegionTest.cpp
Labels: API_BREAKING_CHANGE, encoder, ready

#328 cleanup namespaces
  src/CMakeLists.txt
  src/nupic/algorithms/ArrayBuffer.hpp
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/regions/VectorFile.cpp
  src/nupic/utils/Random.cpp
  src/test/unit/algorithms/AnomalyTest.cpp
  src/test/unit/algorithms/Cells4Test.cpp
  src/test/unit/algorithms/ConnectionsTest.cpp
  src/test/unit/algorithms/SegmentTest.cpp
  src/test/unit/encoders/ScalarEncoderTest.cpp
  src/test/unit/engine/InputTest.cpp
  src/test/unit/engine/LinkTest.cpp
  src/test/unit/engine/NetworkTest.cpp
  src/test/unit/engine/WatcherTest.cpp
  src/test/unit/engine/YAMLUtilsTest.cpp
  src/test/unit/math/TopologyTest.cpp
  src/test/unit/ntypes/ArrayTest.cpp
  src/test/unit/ntypes/CollectionTest.cpp
  src/test/unit/ntypes/DimensionsTest.cpp
  src/test/unit/ntypes/ScalarTest.cpp
  src/test/unit/ntypes/ValueTest.cpp
  src/test/unit/os/EnvTest.cpp
  src/test/unit/os/OSTest.cpp
  src/test/unit/os/PathTest.cpp
  src/test/unit/os/TimerTest.cpp
  src/test/unit/types/BasicTypeTest.cpp
  src/test/unit/types/ExceptionTest.cpp
  src/test/unit/types/SdrProxyTest.cpp
  src/test/unit/types/SdrTest.cpp
  src/test/unit/utils/GroupByTest.cpp
  src/test/unit/utils/MovingAverageTest.cpp
  src/test/unit/utils/SdrMetricsTest.cpp
  src/test/unit/utils/SlidingWindowTest.cpp
  src/test/unit/utils/VectorHelpersTest.cpp
Labels: code, ready

#330 Sdr Tools Organization
  bindings/py/cpp_src/bindings/sdr/py_SDR.cpp
  bindings/py/cpp_src/bindings/sdr/py_SDR_Metrics.cpp
  src/CMakeLists.txt
  src/nupic/algorithms/Connections.hpp
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/encoders/BaseEncoder.hpp
  src/nupic/encoders/ScalarEncoder.cpp
  src/nupic/types/Sdr.hpp
  src/nupic/types/SdrProxy.hpp
  src/nupic/types/SdrTools.cpp
  src/nupic/types/SdrTools.hpp
  src/test/CMakeLists.txt
  src/test/unit/encoders/ScalarEncoderTest.cpp
  src/test/unit/regions/RegionTestUtilities.cpp
  src/test/unit/types/SdrTest.cpp
  src/test/unit/types/SdrToolsTest.cpp
  src/test/unit/utils/SdrMetricsTest.cpp
Labels: code, ready, sdr

#333 Overlap Metric Reset
  bindings/py/cpp_src/bindings/sdr/py_SDR_Metrics.cpp
  bindings/py/tests/sdr/Metrics_test.py
  src/CMakeLists.txt
  src/nupic/utils/SdrMetrics.cpp
  src/nupic/utils/SdrMetrics.hpp
Labels: enhancement, ready, sdr

#334 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: community, documentation

#323 A lightweight Dimensions class
  bindings/py/cpp_src/CMakeLists.txt
  bindings/py/cpp_src/bindings/engine/py_Engine.cpp
  bindings/py/packaging/setup.py
  bindings/py/packaging/src/nupic/bindings/__init__.py
  bindings/py/packaging/src/nupic/bindings/check.py
  bindings/py/tests/sparse_link_test.py
  src/CMakeLists.txt
  src/nupic/engine/Input.cpp
  src/nupic/ntypes/Dimensions.cpp
  src/nupic/ntypes/Dimensions.hpp
  src/nupic/regions/TMRegion.cpp
  src/nupic/regions/TestNode.cpp
  src/test/unit/encoders/ScalarEncoderTest.cpp
  src/test/unit/engine/HelloRegionTest.cpp
  src/test/unit/engine/LinkTest.cpp
  src/test/unit/ntypes/DimensionsTest.cpp
  startupMSVC.bat
Labels: on_hold

#339 Fixes the dependancies for air-gap computers.
  README.md
  external/Boost.cmake
  external/CMakeLists.txt
  external/YamlCppLib.cmake
  external/bootstrap.cmake
  external/eigen.cmake
  external/gtest.cmake
  external/mnist_data.cmake
  external/pybind11.cmake
Labels: ready

#338 TM cleanup
  src/nupic/algorithms/TemporalMemory.cpp
  src/nupic/algorithms/TemporalMemory.hpp
Labels: code, ready

#341 SDR Python bindings use shared_ptr
  bindings/py/cpp_src/bindings/sdr/py_SDR.cpp
  bindings/py/tests/sdr/SDR_test.py
Labels: Python Binding, fix, ready, sdr

#340 Remove all persistentSize methods
  bindings/py/cpp_src/bindings/algorithms/py_Cells4.cpp
  bindings/py/cpp_src/bindings/algorithms/py_HTM.cpp
  src/nupic/algorithms/Cell.hpp
  src/nupic/algorithms/Cells4.hpp
  src/nupic/algorithms/SDRClassifier.cpp
  src/nupic/algorithms/SDRClassifier.hpp
  src/nupic/algorithms/Segment.hpp
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/algorithms/SpatialPooler.hpp
Labels: code, ready

#342 New script rf_view_ScalarEncoder.py
  bindings/py/cpp_src/bindings/encoders/py_ScalarEncoder.cpp
  bindings/py/packaging/src/nupic/examples/__init__.py
  bindings/py/packaging/src/nupic/examples/rf_view_ScalarEncoder.py
  bindings/py/tests/encoders/scalar_encoder_test.py
  src/nupic/encoders/ScalarEncoder.hpp
Labels: encoder, enhancement, example, python, ready

#278 Encoders: Random Distributed Scalar Encoder - WIP
  bindings/py/cpp_src/CMakeLists.txt
  bindings/py/cpp_src/bindings/encoders/encoders_module.cpp
  bindings/py/cpp_src/bindings/encoders/py_RDSE.cpp
  bindings/py/tests/encoders/rdse_test.py
  src/CMakeLists.txt
  src/nupic/encoders/BaseEncoder.hpp
  src/nupic/encoders/RandomDistributedScalarEncoder.cpp
  src/nupic/encoders/RandomDistributedScalarEncoder.hpp
  src/nupic/utils/MurmurHash3.cpp
  src/nupic/utils/MurmurHash3.hpp
  src/test/CMakeLists.txt
  src/test/unit/encoders/RandomDistributedScalarEncoderTest.cpp
Labels: encoder, feature, ready
