Repository htm-community/htm.core, pull requests merged in 2019-01, with the labels that each got.

#197 SP Exact Output Test
  src/nupic/algorithms/SpatialPooler.cpp
  src/nupic/ntypes/Sdr.hpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
Labels: SP, ready, tests

#198 combines types/types.h into types.hpp
  src/CMakeLists.txt
  src/nupic/engine/Link.cpp
  src/nupic/engine/RegionParameters.cpp
  src/nupic/math/Domain.hpp
  src/nupic/math/SparseTensor.hpp
  src/nupic/ntypes/ArrayBase.hpp
  src/nupic/ntypes/Scalar.hpp
  src/nupic/ntypes/Value.hpp
  src/nupic/regions/VectorFileEffector.hpp
  src/nupic/regions/VectorFileSensor.cpp
  src/nupic/regions/VectorFileSensor.hpp
  src/nupic/types/BasicType.hpp
  src/nupic/types/Types.h
  src/nupic/types/Types.hpp
  src/nupic/utils/Watcher.cpp
  src/test/unit/math/SparseBinaryMatrixTest.cpp
  src/test/unit/math/SparseMatrixTest.cpp
Labels: ready

#195 Remove method Connections::minPermanenceSynapse_
  src/nupic/algorithms/Connections.cpp
  src/nupic/algorithms/Connections.hpp
Labels: TM, code, ready

#184 SDR Metrics classes
  src/nupic/ntypes/Sdr.hpp
  src/nupic/ntypes/SdrMetrics.hpp
  src/nupic/ntypes/SdrProxy.hpp
  src/test/CMakeLists.txt
  src/test/unit/ntypes/SdrMetricsTest.cpp
  src/test/unit/ntypes/SdrProxyTest.cpp
  src/test/unit/ntypes/SdrTest.cpp
Labels: enhancement, research

#200 ConnectionsPerformanceTest: improvements
  src/nupic/os/Timer.cpp
  src/test/unit/algorithms/ConnectionsPerformanceTest.cpp
Labels: SP, fix, ready, tests

#190 Connections: cleanup & optimize
  src/nupic/algorithms/Connections.cpp
  src/nupic/algorithms/Connections.hpp
  src/nupic/algorithms/SpatialPooler.cpp
Labels: code, enhancement, ready

#202 Builds in C++17 on Ubuntu
  .travis.yml
  CMakeLists.txt
  CommonCompilerConfig.cmake
  bindings/py/cpp_src/CMakeLists.txt
  bindings/py/cpp_src/bindings/math/py_Math.cpp
  bindings/py/cpp_src/bindings/suppress_register.hpp
  src/CMakeLists.txt
  src/nupic/algorithms/SDRClassifier.cpp
  src/nupic/math/Functions.hpp
  src/nupic/math/Math.hpp
  src/nupic/ntypes/Collection.hpp
  src/nupic/os/Path.cpp
Labels: ready

#192 Random seed from system time
  src/nupic/utils/Random.cpp
  src/nupic/utils/Random.hpp
Labels: code, enhancement, ready

#208 Circle-ci fix
  circle.yml
Labels: build, fix, ready

#206 SpatialPooler always applies boosting.
  src/nupic/algorithms/SpatialPooler.cpp
Labels: SP, ready

#210 Sdr fixups
  src/nupic/ntypes/Sdr.hpp
  src/nupic/ntypes/SdrProxy.hpp
  src/test/unit/ntypes/SdrMetricsTest.cpp
  src/test/unit/ntypes/SdrProxyTest.cpp
  src/test/unit/ntypes/SdrTest.cpp
Labels: code, ready

#212 Python3 compatibility
  bindings/py/packaging/src/nupic/bindings/check.py
  bindings/py/packaging/src/nupic/bindings/regions/PyRegion.py
  bindings/py/packaging/src/nupic/bindings/regions/TestNode.py
  bindings/py/packaging/src/nupic/bindings/tools/cyclical_serialization_perf.py
  bindings/py/packaging/src/nupic/bindings/tools/random_serialization_perf.py
  bindings/py/tests/algorithms/cells4_test.py
  bindings/py/tests/network_test.py
  bindings/py/tests/nupic_random_test.py
  bindings/py/tests/sparse_binary_matrix_test.py
  bindings/py/tests/sparse_matrix_test.py
  setup.py
Labels: enhancement

#180 TM accept external predictive input
  src/nupic/algorithms/TemporalMemory.cpp
  src/nupic/algorithms/TemporalMemory.hpp
  src/test/unit/algorithms/TemporalMemoryTest.cpp
Labels: TM, enhancement, ready

#217 Numenta sync
  src/nupic/math/ArrayAlgo.hpp
Labels: upstream

#224 MSVC_part2
  API_CHANGELOG.md
  CMakeLists.txt
  CommonCompilerConfig.cmake
  DEPENDENCIES.md
  README.md
  appveyor.yml
  bindings/py/cpp_src/bindings/module.cpp
  bindings/py/packaging/dummy.c
  bindings/py/packaging/requirements.txt
  bindings/py/packaging/src/nupic/bindings/__init__.py
  bindings/py/tests/sparse_matrix_test.py
  circle.yml
  external/YamlCppLib.cmake
  src/CMakeLists.txt
  src/examples/HelloSPTP.cpp
  src/nupic/engine/Network.hpp
  src/nupic/engine/Region.cpp
  src/nupic/ntypes/Array.hpp
  src/nupic/regions/TestNode.cpp
  src/nupic/regions/VectorFile.cpp
  src/nupic/regions/VectorFile.hpp
  src/nupic/regions/VectorFileSensor.cpp
  src/nupic/utils/Log.hpp
  src/test/CMakeLists.txt
  src/test/unit/algorithms/ConnectionsPerformanceTest.cpp
  src/test/unit/engine/CppRegionTest.cpp
  src/test/unit/engine/Data.csv
  src/test/unit/engine/HelloRegionTest.cpp
  startupMSVC.bat
Labels: Python Binding, platform, ready

#233 New method SDR::initialize()
  src/nupic/ntypes/Sdr.hpp
Labels: ready

#236 Remove unused algorithms: BitHistory, Scanning::computeAlpha, DynamicLibrary
  src/CMakeLists.txt
  src/nupic/algorithms/BitHistory.cpp
  src/nupic/algorithms/BitHistory.hpp
  src/nupic/algorithms/Scanning.hpp
  src/nupic/os/DynamicLibrary.cpp
  src/nupic/os/DynamicLibrary.hpp
Labels: API_BREAKING_CHANGE, code, ready

#238 Valgrind
  .travis.yml
  README.md
  bindings/py/cpp_src/plugin/unittest/PyRegionTest.cpp
  src/examples/HelloSPTP.cpp
  src/examples/Hotgym.cpp
  src/test/unit/engine/CppRegionTest.cpp
Labels: ready, tests, tooling

#239 Readme: update formating
  README.md
Labels: ready
