Repository htm-community/htm.core, pull requests merged in 2019-11, with the labels that each got.

#738 Panda vis readme
  README.md
  docs/images/pandaVis1.png
Labels: community, documentation

#743 TM.getPredictiveCells improved
  src/htm/algorithms/Connections.cpp
  src/htm/algorithms/TemporalMemory.cpp
Labels: TM, code, ready

#741 Fix for pickling a Network
  bindings/py/cpp_src/bindings/engine/py_Engine.cpp
  bindings/py/cpp_src/plugin/PyBindRegion.cpp
  bindings/py/cpp_src/plugin/RegisteredRegionImplPy.hpp
  bindings/py/tests/regions/__init__.py
  bindings/py/tests/regions/network_test.py
  bindings/py/tests/regions/pyregion_test.py
  src/htm/engine/Network.cpp
  src/htm/engine/Network.hpp
  src/test/unit/engine/NetworkTest.cpp
Labels: Python Binding, ready, serializable

#747 Continuation of fixes for Pickled networkAPI
  bindings/py/cpp_src/bindings/engine/py_Engine.cpp
  bindings/py/cpp_src/plugin/PyBindRegion.cpp
  bindings/py/cpp_src/plugin/PyBindRegion.hpp
  bindings/py/cpp_src/plugin/RegisteredRegionImplPy.hpp
  bindings/py/packaging/src/htm/bindings/regions/PyRegion.py
  bindings/py/tests/regions/pyregion_test.py
  py/tests/advanced/regions/L46aNetwork_test.py
  setup.py
  src/htm/engine/Input.cpp
  src/htm/engine/Network.cpp
  src/htm/engine/Network.hpp
  src/htm/engine/NuPIC.cpp
  src/htm/engine/NuPIC.hpp
  src/htm/engine/Region.cpp
  src/htm/engine/Region.hpp
  src/htm/engine/RegionImplFactory.cpp
  src/htm/engine/RegionImplFactory.hpp
Labels: Python Binding, ready, serializable

#742 Cleanup exceptions
  bindings/py/cpp_src/bindings/engine/py_Engine.cpp
  bindings/py/tests/regions/network_test.py
  src/CMakeLists.txt
  src/htm/engine/Input.cpp
  src/htm/engine/Link.cpp
  src/htm/engine/Network.cpp
  src/htm/engine/Network.hpp
  src/htm/engine/Output.cpp
  src/htm/engine/RegionImpl.cpp
  src/htm/regions/SPRegion.cpp
  src/htm/regions/ScalarSensor.cpp
  src/htm/regions/TMRegion.cpp
  src/htm/regions/TestNode.cpp
  src/htm/regions/VectorFileEffector.cpp
  src/htm/regions/VectorFileSensor.cpp
  src/htm/types/Exception.hpp
  src/htm/utils/Log.hpp
  src/htm/utils/LogItem.cpp
  src/htm/utils/LogItem.hpp
  src/htm/utils/LoggingException.cpp
  src/htm/utils/LoggingException.hpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
  src/test/unit/regions/TMRegionTest.cpp
  src/test/unit/regions/VectorFileTest.cpp
  src/test/unit/utils/RandomTest.cpp
Labels: NetworkAPI, bug, code, ready

#739 Anomaly score calculation separated to own function
  bindings/py/cpp_src/bindings/algorithms/py_TemporalMemory.cpp
  py/htm/algorithms/anomaly.py
  py/tests/algorithms/anomaly_test.py
  src/htm/algorithms/Anomaly.cpp
  src/htm/algorithms/TemporalMemory.cpp
  src/htm/algorithms/TemporalMemory.hpp
Labels: anomaly, in_progress, python

#750 Added std::string (NTA_BasicType_Str) arrays to Array object
  bindings/py/cpp_src/bindings/engine/py_Engine.cpp
  src/htm/ntypes/Array.hpp
  src/htm/ntypes/ArrayBase.cpp
  src/htm/ntypes/ArrayBase.hpp
  src/htm/ntypes/BasicType.cpp
  src/htm/types/Types.hpp
  src/test/unit/ntypes/ArrayTest.cpp
  src/test/unit/ntypes/BasicTypeTest.cpp
Labels: NetworkAPI, ready

#746 Connections create synapse improvements
  src/examples/hotgym/HelloSPTP.cpp
  src/htm/algorithms/Connections.cpp
  src/htm/algorithms/Connections.hpp
  src/htm/algorithms/TemporalMemory.cpp
  src/test/unit/algorithms/ConnectionsTest.cpp
Labels: bug, enhancement, optimization, ready

#754 Added functional test for unpickle of spacial pooler binding
  bindings/py/tests/algorithms/spatial_pooler_test.py
Labels: Python Binding, serializable

#755 fixed Exception copy constructor, expanded what()
  src/htm/types/Exception.hpp
  src/test/unit/types/ExceptionTest.cpp
Labels: fix, ready

#756 Mnist update
  py/htm/examples/mnist.py
Labels: example, python

#757 Region for RDSE Encoder
  src/CMakeLists.txt
  src/htm/engine/Region.hpp
  src/htm/engine/RegionImpl.hpp
  src/htm/engine/RegionImplFactory.cpp
  src/htm/engine/Spec.cpp
  src/htm/engine/Spec.hpp
  src/htm/ntypes/Value.cpp
  src/htm/regions/RDSERegion.cpp
  src/htm/regions/RDSERegion.hpp
  src/htm/types/Exception.hpp
  src/test/CMakeLists.txt
  src/test/unit/regions/RDSERegionTest.cpp
  src/test/unit/regions/SPRegionTest.cpp
  src/test/unit/types/ExceptionTest.cpp
Labels: NetworkAPI, feature, ready

#759 Scalar sensor test
  src/htm/engine/Region.cpp
  src/htm/engine/Region.hpp
  src/htm/regions/ScalarSensor.cpp
  src/test/CMakeLists.txt
  src/test/unit/regions/ScalarSensorTest.cpp
Labels: NetworkAPI, ready, tests

#760 Example implemented using NetworkAPI
  bindings/py/tests/regions/network_test.py
  src/CMakeLists.txt
  src/examples/hotgym/HelloSPTP.cpp
  src/examples/napi_sine/README.md
  src/examples/napi_sine/napi_sine.cpp
  src/htm/algorithms/SpatialPooler.hpp
  src/htm/regions/RDSERegion.cpp
  src/htm/regions/RDSERegion.hpp
  src/htm/regions/SPRegion.cpp
  src/htm/regions/TMRegion.cpp
  src/htm/utils/Random.hpp
  src/test/unit/engine/CppRegionTest.cpp
  src/test/unit/regions/RDSERegionTest.cpp
  src/test/unit/regions/TMRegionTest.cpp
Labels: NetworkAPI, example, ready
