Repository htm-community/htm.core, pull requests merged in 2020-09, with the labels that each got.

#783 SP local inhibition optimization
  bindings/py/cpp_src/bindings/algorithms/py_SpatialPooler.cpp
  bindings/py/cpp_src/bindings/math/py_Topology.cpp
  src/examples/hello/HelloSPTP.cpp
  src/htm/algorithms/SpatialPooler.cpp
  src/htm/algorithms/SpatialPooler.hpp
  src/htm/utils/Topology.cpp
  src/htm/utils/Topology.hpp
  src/test/CMakeLists.txt
  src/test/unit/algorithms/SpatialPoolerTest.cpp
  src/test/unit/engine/RESTapiTest.cpp
  src/test/unit/utils/TopologyTest.cpp
Labels: SP, optimization, ready

#883 bump cpp-httplib version to v0.7.6 latest
  README.md
  bindings/py/cpp_src/CMakeLists.txt
  external/cpp-httplib.cmake
  src/CMakeLists.txt
  src/examples/rest/client.cpp
  src/examples/rest/server_core.hpp
  src/test/CMakeLists.txt
  src/test/unit/engine/RESTapiTest.cpp
Labels: dependencies, ready

#825 Connections growSynapse in C++
  bindings/py/cpp_src/bindings/algorithms/py_Connections.cpp
  py/htm/advanced/algorithms/apical_tiebreak_temporal_memory.py
  py/htm/advanced/algorithms/connections.py
  py/htm/advanced/algorithms/location_modules.py
  py/htm/advanced/algorithms/thalamus.py
  src/htm/algorithms/Connections.cpp
  src/htm/algorithms/Connections.hpp
  src/htm/algorithms/TemporalMemory.cpp
Labels: optimization, ready

#886 Missing includes
  README.md
  src/CMakeLists.txt
  src/examples/napi_hello/DebugBuild.sh
  src/examples/napi_hello/ReleaseBuild.sh
  src/examples/napi_hello/napi_hello.cpp
  src/examples/napi_hello/napi_hello.hpp
  src/examples/napi_hello/napi_hello_database.cpp
  src/htm/engine/Region.hpp
  src/htm/ntypes/Array.hpp
  src/htm/os/ImportFilesystem.hpp
  src/htm/os/Timer.cpp
  src/htm/os/Timer.hpp
Labels: NetworkAPI, example

#873 Serializing connections objects through NetworkAPI
  bindings/py/cpp_src/bindings/engine/py_Region.cpp
  docs/NetworkAPI.md
  py/htm/advanced/regions/ApicalTMPairRegion.py
  py/htm/advanced/regions/ApicalTMSequenceRegion.py
  py/htm/advanced/regions/ColumnPoolerRegion.py
  py/htm/examples/networkAPI/hotgym.py
  src/htm/regions/SPRegion.cpp
  src/htm/regions/TMRegion.cpp
  src/htm/regions/TMRegion.hpp
  src/test/unit/regions/TMRegionTest.cpp
Labels: NetworkAPI, enhancement, example
