Repository htm-community/htm.core, pull requests merged in 2020-04, with the labels that each got.

#787 completed the .py rest example
  py/htm/examples/rest/client.py
  setup.py
  src/examples/hello/HelloSPTP.cpp
  src/examples/rest/README.md
Labels: REST, ready

#789 GCC 9 / ubuntu 20.04 support
  bindings/py/packaging/dummy.c
Labels: build, platform, ready

#791 Added helps to README
  README.md
Labels: documentation, ready

#794 param differences docs
  API_DIFFERENCES.md
  README.md
Labels: API_BREAKING_CHANGE, community, documentation

#798 fixed problem with boost not finding library
  external/Boost.cmake
Labels: build, ready

#797 Sp reintroduce num active columns per inh area
  VERSION
  bindings/py/cpp_src/bindings/algorithms/py_SpatialPooler.cpp
  src/examples/mnist/MNIST_SP.cpp
  src/htm/algorithms/SpatialPooler.cpp
  src/htm/algorithms/SpatialPooler.hpp
  src/htm/regions/SPRegion.cpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
  src/test/unit/regions/SPRegionTest.cpp
Labels: API_BREAKING_CHANGE, SP, code, ready
