Repository htm-community/htm.core, pull requests merged in 2020-08, with the labels that each got.

#866 Added the ability to access Spec and parameters as JSON from Python
  API_CHANGELOG.md
  bindings/py/cpp_src/bindings/engine/py_Engine.cpp
  bindings/py/cpp_src/plugin/PyBindRegion.cpp
  bindings/py/cpp_src/plugin/PyBindRegion.hpp
  bindings/py/packaging/src/htm/bindings/regions/PyRegion.py
  py/htm/advanced/regions/ApicalTMPairRegion.py
  py/htm/advanced/regions/ColumnPoolerRegion.py
  py/htm/advanced/regions/GridCellLocationRegion.py
  py/tests/networkapi/getParameters_test.py
  py/tests/networkapi/sinewave_test.py
  src/htm/engine/Network.cpp
  src/htm/engine/Network.hpp
  src/htm/engine/RESTapi.cpp
  src/htm/engine/Region.cpp
  src/htm/engine/Region.hpp
  src/htm/engine/RegionImpl.cpp
  src/htm/engine/RegionImpl.hpp
  src/htm/engine/RegionImplFactory.cpp
  src/htm/engine/RegionImplFactory.hpp
  src/htm/engine/RegisteredRegionImplCpp.hpp
  src/htm/engine/Spec.cpp
  src/htm/ntypes/Array.hpp
  src/htm/ntypes/ArrayBase.cpp
  src/htm/ntypes/ArrayBase.hpp
  src/htm/ntypes/Value.cpp
  src/htm/regions/ClassifierRegion.cpp
  src/htm/regions/ClassifierRegion.hpp
  src/htm/regions/DatabaseRegion.cpp
  src/htm/regions/DatabaseRegion.hpp
  src/htm/regions/DateEncoderRegion.cpp
  src/htm/regions/DateEncoderRegion.hpp
  src/htm/regions/FileInputRegion.cpp
  src/htm/regions/FileInputRegion.hpp
  src/htm/regions/FileOutputRegion.cpp
  src/htm/regions/FileOutputRegion.hpp
  src/htm/regions/RDSEEncoderRegion.cpp
  src/htm/regions/RDSEEncoderRegion.hpp
  src/htm/regions/SPRegion.cpp
  src/htm/regions/SPRegion.hpp
  src/htm/regions/ScalarEncoderRegion.cpp
  src/htm/regions/ScalarEncoderRegion.hpp
  src/htm/regions/TMRegion.cpp
  src/htm/regions/TMRegion.hpp
  src/htm/regions/TestNode.cpp
  src/htm/regions/TestNode.hpp
  src/htm/regions/VectorFile.cpp
  src/htm/regions/VectorFile.hpp
  src/test/unit/regions/ClassifierRegionTest.cpp
  src/test/unit/regions/DatabaseRegionTest.cpp
  src/test/unit/regions/DateEncoderRegionTest.cpp
  src/test/unit/regions/ScalarEncoderRegionTest.cpp
Labels: NetworkAPI

#867 Trailing comma in JSON not allowed
  py/tests/networkapi/getParameters_test.py
  py/tests/networkapi/sinewave_test.py
  src/htm/engine/Region.cpp
  src/htm/engine/Spec.cpp
  src/test/unit/regions/ClassifierRegionTest.cpp
  src/test/unit/regions/DatabaseRegionTest.cpp
  src/test/unit/regions/DateEncoderRegionTest.cpp
  src/test/unit/regions/ScalarEncoderRegionTest.cpp
Labels: bug, ready

#871 Doc python developmode
  README.md
Labels: documentation

#879 fixed getParameters
  src/htm/ntypes/Array.hpp
  src/htm/regions/SPRegion.cpp
  src/test/unit/engine/HelloRegionTest.cpp
  src/test/unit/regions/RDSEEncoderRegionTest.cpp
  src/test/unit/regions/RegionTestUtilities.cpp
  src/test/unit/regions/SPRegionTest.cpp
  src/test/unit/regions/ScalarEncoderRegionTest.cpp
  src/test/unit/regions/TMRegionTest.cpp
Labels: NetworkAPI, fix, ready
