Repository htm-community/htm.core, pull requests merged in 2020-07, with the labels that each got.

#849 Expanded REST response to include type and dim's
  src/htm/algorithms/TemporalMemory.cpp
  src/htm/engine/RESTapi.cpp
  src/htm/engine/Region.cpp
  src/htm/engine/Region.hpp
  src/htm/ntypes/ArrayBase.cpp
  src/htm/ntypes/Dimensions.hpp
  src/htm/regions/TMRegion.cpp
  src/test/unit/algorithms/ConnectionsPerformanceTest.cpp
  src/test/unit/engine/RESTapiTest.cpp
  src/test/unit/ntypes/DimensionsTest.cpp
Labels: REST, fix, ready

#856 Examples run in CI
  .github/workflows/pr.yml
  src/examples/mnist/MNIST_SP.cpp
Labels: example, ready

#857 Added sqlite3 as third party package
  external/CMakeLists.txt
  external/bootstrap.cmake
  external/sqlite3.cmake
  src/CMakeLists.txt
Labels: build, dependencies, ready

#859 Added unit test for sqlite3
  README.md
  external/sqlite3.cmake
  src/test/CMakeLists.txt
  src/test/unit/utils/Sqlite3Test.cpp
Labels: build, dependencies, ready

#862 Htm advanced doc update
  py/htm/advanced/README.md
  py/htm/advanced/examples/thalamus/README.md
  py/htm/advanced/frameworks/location/location_network_creation.py
  setup.py
Labels: bug, documentation
