Repository htm-community/htm.core, pull requests merged in 2020-06, with the labels that each got.

#804 Fixing ARM64 CI
  .github/workflows/build.yml
  README.md
  requirements.txt
Labels: build, platform, tooling

#805 CI PyPI cibuildwheel
  .github/workflows/arm.yml
  .github/workflows/build.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: release, tooling

#819 CI CIBW pypi releases
  .github/workflows/arm.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  Dockerfile-pypi
  README.md
  RELEASE.md
Labels: tooling

#824 optimize for-loops
  src/htm/algorithms/Connections.cpp
  src/htm/algorithms/Connections.hpp
  src/htm/algorithms/SpatialPooler.cpp
  src/htm/algorithms/TemporalMemory.cpp
Labels: code, optimization, ready

#822 TM: add test for large input performance
  bindings/py/tests/algorithms/temporal_memory_test.py
Labels: TM, tests

#601 Fix Connections segment pruning
  VERSION
  bindings/py/cpp_src/bindings/algorithms/py_Connections.cpp
  bindings/py/tests/algorithms/connections_test.py
  py/tests/advanced/algorithms/advanced_connections_test.py
  src/examples/hello/HelloSPTP.cpp
  src/htm/algorithms/Connections.cpp
  src/htm/algorithms/Connections.hpp
  src/htm/algorithms/TemporalMemory.cpp
  src/test/unit/algorithms/ConnectionsPerformanceTest.cpp
Labels: bug, fix, ready

#826 Random: cleanup & pickle
  bindings/py/cpp_src/bindings/math/py_Random.cpp
  src/htm/utils/Random.cpp
  src/htm/utils/Random.hpp
  src/test/unit/utils/RandomTest.cpp
Labels: code, ready

#827 Connections: serialization, op==
  src/htm/algorithms/Connections.cpp
  src/htm/algorithms/Connections.hpp
Labels: code, ready, serializable

#830 Implemented DELETE operator for REST.
  .gitignore
  docs/NetworkAPI_REST.md
  src/examples/rest/server_core.hpp
  src/htm/engine/RESTapi.cpp
  src/htm/engine/RESTapi.hpp
  src/test/unit/engine/RESTapiTest.cpp
Labels: REST, ready

#833 create network with a custom id when force param is set
  src/examples/rest/server_core.hpp
  src/htm/engine/RESTapi.cpp
Labels: NetworkAPI

#836 Fixed rest server custom host error
  src/examples/rest/server.cpp
Labels: NetworkAPI, fix

#834 Rest api client
  py/htm/examples/rest/README.md
  py/htm/examples/rest/client.py
  py/htm/examples/rest/hotgym.py
  py/htm/examples/rest/htm_rest_api.py
  py/tests/rest/htm_rest_api_test.py
  requirements.txt
Labels: REST, enhancement

#837 Allowed variation in POST, added unit test
  src/examples/rest/server_core.hpp
  src/htm/algorithms/Connections.hpp
  src/htm/engine/RESTapi.cpp
  src/htm/engine/RESTapi.hpp
  src/htm/utils/Random.hpp
  src/test/unit/engine/RESTapiTest.cpp
Labels: REST, ready

#841 Allows default values in spec to be JSON syntax
  py/htm/examples/rest/htm_rest_api.py
  py/tests/rest/htm_rest_api_test.py
  src/CMakeLists.txt
  src/htm/algorithms/SpatialPooler.cpp
  src/htm/algorithms/TemporalMemory.cpp
  src/htm/engine/Input.cpp
  src/htm/engine/RegionImpl.cpp
  src/htm/engine/Watcher.cpp
  src/htm/ntypes/Array.hpp
  src/htm/ntypes/ArrayBase.cpp
  src/htm/ntypes/Value.cpp
  src/htm/regions/TestNode.cpp
  src/test/CMakeLists.txt
  src/test/unit/engine/CppRegionTest.cpp
  src/test/unit/engine/RESTapiTest.cpp
  src/test/unit/ntypes/ValueTest.cpp
Labels: NetworkAPI, bug, fix, ready

#846 Suppress warning STL4014
  CommonCompilerConfig.cmake
Labels: build, fix, ready

#848 Eigen relocation
  README.md
  external/CMakeLists.txt
  external/YamlCppLib.cmake
  external/eigen.cmake
  src/htm/ntypes/Value.cpp
Labels: dependencies

#851 README update - Corrected typo and pandaVis image update
  README.md
  docs/images/pandaVis1.png
Labels: documentation

#853 NetworkAPI How to create regions.
  README.md
  docs/NetorkAPI_Creating_Regions.md
  docs/NetworkAPI.md
  docs/NetworkAPI_Regions.md
Labels: documentation

#854 corrected broken links
  docs/NetworkAPI.md
Labels: NetworkAPI, documentation, ready
