Repository htm-community/htm.core, pull requests merged in 2020-02, with the labels that each got.

#561 SP Connections integration
  bindings/py/cpp_src/bindings/algorithms/py_Connections.cpp
  bindings/py/cpp_src/bindings/algorithms/py_SpatialPooler.cpp
  bindings/py/tests/algorithms/connections_test.py
  bindings/py/tests/algorithms/spatial_pooler_test.py
  bindings/py/tests/algorithms/temporal_memory_test.py
  src/examples/hotgym/HelloSPTP.cpp
  src/htm/algorithms/SpatialPooler.cpp
  src/htm/algorithms/SpatialPooler.hpp
  src/htm/algorithms/TemporalMemory.cpp
  src/htm/algorithms/TemporalMemory.hpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
  src/test/unit/algorithms/TemporalMemoryTest.cpp
Labels: SP, code

#768 TM.getLeastUsedCell improved
  bindings/py/tests/regions/network_test.py
  src/examples/hotgym/HelloSPTP.cpp
  src/htm/algorithms/TemporalMemory.cpp
  src/htm/algorithms/TemporalMemory.hpp
  src/test/unit/algorithms/TemporalMemoryTest.cpp
Labels: TM, code, ready

#772 Adding licenses to README.md
  README.md
Labels: documentation, ready

#769 Optimizations to local inhibition
  src/htm/algorithms/SpatialPooler.cpp
Labels: SP, optimization

#775 ae.py changes to allow execution on windows.
  py/htm/optimization/ae.py
Labels: platform
