Repository htm-community/htm.core, pull requests merged in 2021-02, with the labels that each got.

#909 initialized the array per issue #908
  bindings/py/cpp_src/bindings/algorithms/py_SpatialPooler.cpp
  src/htm/algorithms/SpatialPooler.cpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
Labels: Python Binding

#913 deps: bump pybind11 to 2.6.x releases
  external/pybind11.cmake
Labels: dependencies

#912 Add method RDSE.check_parameters()
  bindings/py/cpp_src/bindings/encoders/py_RDSE.cpp
  bindings/py/tests/encoders/rdse_test.py
  src/htm/algorithms/Connections.cpp
  src/htm/encoders/RandomDistributedScalarEncoder.cpp
  src/htm/encoders/RandomDistributedScalarEncoder.hpp
  src/htm/engine/Network.cpp
  src/test/unit/regions/RDSEEncoderRegionTest.cpp
Labels: encoder, enhancement

#914 bump dependency versions
  external/cereal.cmake
  external/cpp-httplib.cmake
  external/digestpp.cmake
  external/eigen.cmake
  external/libYaml.cmake
  external/sqlite3.cmake
Labels: dependencies

#906 implement py_Predictor py_Classifier pickle
  bindings/py/cpp_src/bindings/algorithms/py_SDRClassifier.cpp
Labels: Python Binding, serializable

#915 CI: use ubuntu 20.04
  .github/workflows/arm.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  README.md
Labels: tooling

#820 Use python 3.8 in CI builds
  .github/workflows/pr.yml
  .github/workflows/release.yml
  requirements.txt
  src/test/unit/regions/ClassifierRegionTest.cpp
Labels: python, ready, tooling

#557 Connections try float16 for optimization (float is faster)
  src/htm/algorithms/Connections.cpp
  src/htm/algorithms/Connections.hpp
  src/htm/algorithms/SpatialPooler.cpp
  src/htm/algorithms/SpatialPooler.hpp
  src/htm/algorithms/TemporalMemory.cpp
  src/htm/algorithms/TemporalMemory.hpp
  src/htm/types/Types.hpp
  src/test/unit/algorithms/SpatialPoolerTest.cpp
Labels: code, in_progress, optimization

#916 Gtest update to version10.0
  external/gtest.cmake
Labels: build
